workflows:
  ios_maui_release:
    name: "iOS MAUI Release (.NET 8, Manual Codesign + TestFlight Upload)"
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      # İstersen sabitle: xcode: 16.0
      vars:
        PROJECT_DIR: "LessArcApppp"            # csproj klasörü
        CSPROJ_PATH: "LessArcApppp.csproj"     # csproj dosya adı
        IOS_BUNDLE_ID: "com.nisakara.lessarc"  # App Store Connect ile birebir aynı
      groups:
        - ios_signing        # CM_CERTIFICATE / CM_CERTIFICATE_PASSWORD / CM_PROVISIONING_PROFILE  (base64)
        - app_store_connect  # APP_STORE_CONNECT_PRIVATE_KEY / APP_STORE_CONNECT_KEY_IDENTIFIER / APP_STORE_CONNECT_ISSUER_ID

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet

    scripts:
      - name: .NET 8 ve MAUI yükle
        script: |
          set -euo pipefail
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          bash dotnet-install.sh --channel 8.0 --install-dir "$HOME/.dotnet"
          echo 'export PATH="$HOME/.dotnet:$PATH"' >> $CM_ENV
          echo 'export DOTNET_ROOT="$HOME/.dotnet"' >> $CM_ENV
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --info
          dotnet workload install maui ios

      - name: Keychain hazırla (Codemagic CLI)
        script: |
          set -euo pipefail
          pip3 install --user codemagic-cli-tools
          export PATH="$HOME/Library/Python/3.11/bin:$PATH"
          keychain initialize

      - name: p12 sertifikayı import et
        script: |
          set -euo pipefail
          echo "$CM_CERTIFICATE" | base64 --decode > dist.p12
          keychain add-certificates \
            --certificate dist.p12 \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"
          security find-identity -v -p codesigning

      - name: Provisioning profile’ı yükle + UUID/Identity çıkar
        script: |
          set -euo pipefail
          echo "$CM_PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision
          UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< "$(security cms -D -i profile.mobileprovision)")
          echo "PROFILE UUID: $UUID"
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"

          CODESIGN_IDENTITY=$(security find-identity -v -p codesigning | grep 'Apple Distribution:' | head -n1 | sed -E 's/.*"(.+)"/\1/')
          if [ -z "$CODESIGN_IDENTITY" ]; then
            echo "Code signing identity bulunamadı!"
            exit 1
          fi
          echo "CODESIGN_IDENTITY: $CODESIGN_IDENTITY"

          echo "export PROV_UUID=$UUID" >> $CM_ENV
          echo "export CODESIGN_IDENTITY=\"$CODESIGN_IDENTITY\"" >> $CM_ENV

      - name: NuGet restore
        script: |
          set -euo pipefail
          export PATH="$HOME/.dotnet:$PATH"
          cd "$PROJECT_DIR"
          dotnet restore "$CSPROJ_PATH"

      - name: İmzalı IPA üret (Release, ios-arm64)
        script: |
          set -euo pipefail
          export PATH="$HOME/.dotnet:$PATH"
          [ -f "$CM_ENV" ] && . "$CM_ENV" || true
          cd "$PROJECT_DIR"
          dotnet publish "$CSPROJ_PATH" -f net8.0-ios -c Release \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:ArchiveOnBuild=true \
            -p:BuildIpa=true \
            -p:Codesign=true \
            -p:CodesignKey="$CODESIGN_IDENTITY" \
            -p:CodesignProvision="$PROV_UUID"

      - name: IPA/xcarchive topla
        script: |
          set -euo pipefail
          ART_DIR="${CM_ARTIFACTS_DIR:-$PWD/artifacts}"
          mkdir -p "$ART_DIR"
          find "$PROJECT_DIR/bin/Release/net8.0-ios/ios-arm64" -name "*.ipa" -print -exec cp {} "$ART_DIR" \; || true
          find "$PROJECT_DIR/bin/Release/net8.0-ios/ios-arm64/publish" -name "*.ipa" -print -exec cp {} "$ART_DIR" \; || true
          find "$PROJECT_DIR/bin/Release/net8.0-ios/ios-arm64" -name "*.xcarchive" -print -exec cp -R {} "$ART_DIR" \; || true
          ls -la "$ART_DIR"
          echo "export CM_ARTIFACTS_DIR=\"$ART_DIR\"" >> $CM_ENV

      - name: App Store Connect kimlik testi
        script: |
          set -euo pipefail
          export PATH="$HOME/Library/Python/3.11/bin:$PATH"
          echo "KEY_ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo "ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "PRIVATE_KEY length: $(printf "%s" "$APP_STORE_CONNECT_PRIVATE_KEY" | wc -c)"
          # Doğru alt komut: sadece listeyi çek
          app-store-connect apps list --log-stream stdout

      - name: TestFlight’a yükle (App Store Connect)
        script: |
          set -euo pipefail
          export PATH="$HOME/Library/Python/3.11/bin:$PATH"
          [ -f "$CM_ENV" ] && . "$CM_ENV" || true

          ART_DIR="${CM_ARTIFACTS_DIR:-$PWD/artifacts}"
          IPA="$(ls -1 "$ART_DIR"/*.ipa | head -n 1 || true)"
          if [ -z "$IPA" ]; then
            echo "IPA bulunamadı!"
            ls -la "$ART_DIR" || true
            exit 1
          fi
          echo "Uploading IPA: $IPA"

          app-store-connect publish \
            --path "$IPA" \
            --testflight \
            --bundle-id "$IOS_BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-identifier "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --verbose --log-stream stdout

    artifacts:
      - $CM_ARTIFACTS_DIR/*.ipa
      - artifacts/*.ipa
      - $CM_ARTIFACTS_DIR/*.xcarchive
      - artifacts/*.xcarchive

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
