workflows:
  ios_maui_release:
    name: "iOS MAUI Release (.NET 8, Auto Codesign)"
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        PROJECT_DIR: "LessArcApppp"           # klasörün
        CSPROJ_PATH: "LessArcApppp.csproj"    # csproj dosyan
        IOS_BUNDLE_ID: "com.nisakara.lessarc" # csproj ile aynı
      groups:
        - app_store_connect                   # ISSUER_ID / KEY_IDENTIFIER / PRIVATE_KEY bu grupta

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet

    scripts:
      - name: .NET 8 ve MAUI yükle
        script: |
          set -euo pipefail
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          bash dotnet-install.sh --channel 8.0
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --info
          dotnet workload install maui

      - name: Codemagic CLI + keychain
        script: |
          set -euo pipefail
          pip3 install --user codemagic-cli-tools
          export PATH="$HOME/Library/Python/3.11/bin:$PATH"
          keychain initialize

      - name: App Store Connect’ten imza dosyalarını çek
        script: |
          set -euo pipefail
          app-store-connect fetch-signing-files "$IOS_BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: NuGet restore
        script: |
          set -euo pipefail
          cd "$PROJECT_DIR"
          dotnet restore "$CSPROJ_PATH"

      - name: İmzalı IPA üret (Release, ios-arm64)
        script: |
          set -euo pipefail
          cd "$PROJECT_DIR"
          dotnet publish "$CSPROJ_PATH" -f net8.0-ios -c Release \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:ArchiveOnBuild=true \
            -p:Codesign=true

      - name: IPA/xcarchive topla
        script: |
          set -euo pipefail
          mkdir -p "$CM_ARTIFACTS_DIR"
          find "$PROJECT_DIR/bin/Release/net8.0-ios/ios-arm64" -name "*.ipa" -print -exec cp {} "$CM_ARTIFACTS_DIR" \; || true
          find "$PROJECT_DIR/bin/Release/net8.0-ios/ios-arm64" -name "*.xcarchive" -print -exec cp -R {} "$CM_ARTIFACTS_DIR" \; || true

    artifacts:
      - $CM_ARTIFACTS_DIR/*.ipa
      - $CM_ARTIFACTS_DIR/*.xcarchive

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"   # ana dal: main
          include: true
          source: true
